function [fitresult, gof] = createFit(time, elastance)
%CREATEFIT(T_ISO,EES_ISO)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t_iso
%      Y Output: Ees_iso
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Dec-2020 16:36:40


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( time, elastance );
ft = fittype( 'gauss1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0];
opts.StartPoint = [0.33 0.11 0.05];
% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

end


